import type { Metadata } from "next";
import NavMenu from "../lib/ui/nav/nav-menu";
import styles from './layout.module.scss';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className={styles.header}>
          <NavMenu />
        </header>
        {children}
      </body>
    </html>
  );
}
