import type { Metadata } from "next";
import NavMenu from "../lib/ui/nav/nav-menu";
import styles from './layout.module.scss';
import { Roboto } from '@next/font/google';
import '../globals.scss';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ['latin'], 
  weight: ['400', '700'], // İhtiyacınıza göre ağırlıkları ekleyin
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body className={styles.container}>
        <header className={styles.header}>
          <NavMenu />
        </header>
        {children}
      </body>
    </html>
  );
}
